version: "3.8"

services:
  scraper:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/scrape"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Mount tmp for Playwright temporary files
      - /tmp:/tmp
    security_opt:
      - seccomp:unconfined
    # Add some resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
